version: 1
formatters:
    default:
        format: "[%(asctime)s] %(levelname)s in %(module)s(%(lineno)d): %(message)s"
    application:
        '()': app.logger.CsvFormatter
        format: "%(asctime)s,%(contract_id)s,%(levelname)-5s,%(module)s,%(funcName)s,(%(lineno)d),%(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
handlers: 
    console:
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: default
    application:
        class: logging.handlers.TimedRotatingFileHandler
        formatter: application
        filename: log/application.csv
        when: MIDNIGHT
        backupCount: 31
        encoding: "utf-8"
loggers:
    appLogger:
        level: DEBUG
        handlers: [console,application]
        propagate: no
root:
    level: DEBUG
    handlers: [console]
disable_existing_loggers": false
