"""empty message

Revision ID: 38f14c20edc2
Revises: 
Create Date: 2020-12-24 08:25:28.946729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f14c20edc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Unicode(length=32), nullable=False),
    sa.Column('status', sa.Unicode(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basket_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('contract_id', sa.Unicode(length=32), nullable=False),
    sa.Column('analyzed_result', sa.Text(), nullable=False),
    sa.Column('analysis_condition_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baskets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Unicode(length=32), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('analyze_result', sa.Text(), nullable=False),
    sa.Column('analyze_condition', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basket_analysis_condition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Unicode(length=32), nullable=False),
    sa.Column('basket_analysis_id', sa.Unicode(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['basket_analysis_id'], ['basket_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basket_analysis_store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Unicode(length=32), nullable=False),
    sa.Column('basket_analysis_id', sa.Unicode(length=32), nullable=False),
    sa.Column('store_id', sa.Unicode(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['basket_analysis_id'], ['basket_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket_analysis_store')
    op.drop_table('basket_analysis_condition')
    op.drop_table('baskets')
    op.drop_table('basket_analysis')
    op.drop_table('accounts')
    # ### end Alembic commands ###
