"""empty message

Revision ID: 4fd23444e08e
Revises: 
Create Date: 2020-11-18 13:39:35.344630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd23444e08e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Unicode(length=32), nullable=False),
    sa.Column('status', sa.Unicode(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('auther', sa.Unicode(length=255), nullable=True),
    sa.Column('publisher', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Unicode(length=255), nullable=True),
    sa.Column('book_title', sa.Unicode(length=255), nullable=True),
    sa.Column('impression', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['book_title'], ['books.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diaries2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Unicode(length=255), nullable=True),
    sa.Column('book_title', sa.Unicode(length=255), nullable=True),
    sa.Column('impression', sa.UnicodeText(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_title'], ['books.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diaries2')
    op.drop_table('diaries')
    op.drop_table('books')
    op.drop_table('accounts')
    # ### end Alembic commands ###
