-- upgrade --
CREATE TABLE IF NOT EXISTS `accounts` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `contract_id` VARCHAR(32) NOT NULL,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `modified_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `access_token` VARCHAR(1024) NOT NULL,
    `expiration_date_time` DATETIME(6) NOT NULL,
    `status` VARCHAR(16) NOT NULL
) CHARACTER SET utf8mb4 COMMENT='アカウントモデル';
CREATE TABLE IF NOT EXISTS `daily_basket_list` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `contract_id` VARCHAR(32) NOT NULL,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `modified_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `store_id` INT NOT NULL,
    `target_date` DATE NOT NULL,
    `basket_list` LONGTEXT NOT NULL
) CHARACTER SET utf8mb4 COMMENT='バスケット分析用データモデル';
CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(20) NOT NULL,
    `content` LONGTEXT NOT NULL
) CHARACTER SET utf8mb4;
