-- upgrade --
CREATE TABLE IF NOT EXISTS `account_setting` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `contract_id` VARCHAR(32) NOT NULL,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `modified_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `display_store_id` INT
) CHARACTER SET utf8mb4 COMMENT='アカウント設定モデル';
CREATE TABLE IF NOT EXISTS `accounts` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `contract_id` VARCHAR(32) NOT NULL,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `modified_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `access_token` VARCHAR(1024) NOT NULL,
    `expiration_date_time` DATETIME(6) NOT NULL,
    `status` VARCHAR(16) NOT NULL,
    `account_setting_id` INT NOT NULL UNIQUE,
    CONSTRAINT `fk_accounts_account__69e174ad` FOREIGN KEY (`account_setting_id`) REFERENCES `account_setting` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COMMENT='アカウントモデル';
CREATE TABLE IF NOT EXISTS `daily_basket_list` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `contract_id` VARCHAR(32) NOT NULL,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `modified_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `store_id` INT NOT NULL,
    `target_date` DATE NOT NULL,
    `basket_list` LONGTEXT
) CHARACTER SET utf8mb4 COMMENT='バスケット分析用データモデル';
CREATE TABLE IF NOT EXISTS `products` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `contract_id` VARCHAR(32) NOT NULL,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `modified_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `product_id` INT NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `color` VARCHAR(64),
    `size` VARCHAR(64),
    `image` VARCHAR(511),
    `price` INT,
    `category_id` INT,
    `group_code_id` VARCHAR(255)
) CHARACTER SET utf8mb4 COMMENT='商品モデル';
CREATE TABLE IF NOT EXISTS `stores` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `contract_id` VARCHAR(32) NOT NULL,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `modified_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `store_id` INT NOT NULL,
    `name` VARCHAR(255) NOT NULL
) CHARACTER SET utf8mb4 COMMENT='店舗t品モデル';
CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(20) NOT NULL,
    `content` LONGTEXT NOT NULL
) CHARACTER SET utf8mb4;
